all:
  hosts:
    node1.test.com:
    node2.test.com:
    node3.test.com:
  vars:
    ansible_user: node_user
  children:
    kube_cluster:
      hosts:
        node1.test.com:
        node2.test.com:
        node3.test.com:
    kube_masters:
      hosts:
        kube_master:
          ansible_host: node1.test.com
    kube_workers:
      hosts:
        node2.test.com
        node3.test.com
