---
- name: Add docker repo GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb['codename'] }} stable"
    update_cache: yes

- name: Install docker
  apt:
    name: "docker-ce={{ docker_version }}"
    install_recommends: yes

- name: Freeze docker version
  shell: apt-mark hold docker-ce
